### ISSUE TITLE
Any alternative of SigThief for Linux binaries

### ISSUE THREAD

**Issue by akatheria** [secretsquirrel/SigThief#10]
Hey @secretsquirrel. I have used SigThief on numerous occasions and it worked like a charm. However, I have moved away from the windows environment to the Linux env and was scouring through the internet to find an alternative for Linux bins that works as smoothly as SigThief. Do you have any tool in mind are or are you planning to include this feature in the new release?

**Comment by secretsquirrel** [comment]
It supports python3… There is no code signing on Linux.On Dec 3, 2022, at 7:21 PM, akatheria ***@***.***> wrote:﻿
Hey @secretsquirrel. I have used SigThief on numerous occasions and it worked like a charm. However, I have moved away from the windows environment to the Linux env and was scouring through the internet to find an alternative for Linux bins that works as smoothly as SigThief. Do you have any tool in mind are or are you planning to include this feature in the new release?

**Comment by akatheria** [comment]
Linux binaries are also signed right. I even got a repo https://github.com/NUAA-WatchDog/linux-elf-binary-signer which helps you sign the binary using your self-signed cert. However, this doesn't let me steal signature as SigThief does.

**Comment by secretsquirrel** [comment]
It’s not common.On Dec 3, 2022, at 10:08 PM, akatheria ***@***.***> wrote:﻿
Linux binaries are also signed right. I even got a repo https://github.com/NUAA-WatchDog/linux-elf-binary-signer which helps you sign the binary using your self-signed cert. However, this doesn't let me steal signature as SigThief does.

**Comment by akatheria** [comment]
I have written an executable malware for android OS. It is compiled to run with an aarch64 instruction set. However, I am still getting flagged by the EDRs saying it's a Trojan. However, if I can sign it with a known Linux signed binary like the ones used for RHEL systems I think I can evade that. Hence the requirement.

**Comment by secretsquirrel** [comment]
Do you have examples of Linux signed binaries that you can share? Preferably downloadable from major distro repos.

**Comment by akatheria** [comment]
I could only find Secure boot UEFI to be signed but that's at the hardware level. I have seen multiple embedded systems running modified Linux kernel to implement signature verification using elfsign and elfverify but most of the certificated were from Public CAs. So yeah I could not find any of the binaries after some research. However, my question still remains that since linux kernel supports signature verification and signed binary has it's signature is stored in ELF header what will it take to steal it and use it sign another binary?

Ref : https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_monitoring_and_updating_the_kernel/signing-kernel-modules-for-secure-boot_managing-monitoring-and-updating-the-kernel

**Comment by secretsquirrel** [comment]
I'll put Linux and more so macOS binaires on the roadmap, but it won't be open source.
