### ISSUE TITLE
Input file not signed

### ISSUE THREAD

**Issue by botshake** [secretsquirrel/SigThief#12]
Hey,

Thanks for this awesome tool.
But I'm having trouble using it, as no matter what I do, it always throws this message: "Input file not signed!"
I've tried with cmd.exe, tasklist.exe, systray.exe, but no luck.

What am I doing wrong?

Pls help and thanks!

**Comment by secretsquirrel** [comment]
See this: https://blog.didierstevens.com/2008/01/11/the-case-of-the-missing-digital-signatures-tab/

**Comment by botshake** [comment]
aha, thanks :)
