### ISSUE TITLE
Clones invalid signatures

### ISSUE THREAD

**Issue by graysuit** [secretsquirrel/SigThief#4]
**Here it is Clone signature<br><img src="https://i.ibb.co/4ZRGdyb/cloned.png"><br><br>
Here it is Real signature**<br><img src="https://i.ibb.co/LhPsF1X/orignal.png"><br><br>

**Sir ,
I want to know,
When I clone signature from a file,
And get into properties > Digital signature > Details

It show that signature is invalid,
Even signature is valid when I see original file,
Whats wrong,
Please instruct me If i am doing something wrong

And I done this using this command**

`./sigthief.py -i tcpview.exe -t x86_meterpreter_stager.exe -o /tmp/msftesting_tcpview.exe `

**Comment by secretsquirrel** [comment]
Read this: https://github.com/secretsquirrel/SigThief#what-is-this

**Comment by graysuit** [comment]
Oh I see,
Thanks Mr @secretsquirrel ,
I didn't read full documentation as all of us do,
Sorry for that,

But there should be some way,
From where we can clone valid signatures...
