### ISSUE TITLE
Would this work for a DLL file aswell?

### ISSUE THREAD

**Issue by aqua95** [secretsquirrel/SigThief#5]

**Comment by secretsquirrel** [comment]
Did you try it?

**Comment by aqua95** [comment]
Traceback (most recent call last):
  File "sigthief.py", line 248, in <module>
    writeCert(cert, options.targetfile, options.outputfile)
  File "sigthief.py", line 120, in writeCert
    flItms = gather_file_info_win(exe)
  File "sigthief.py", line 27, in gather_file_info_win
    flItms['MachineType'] = struct.unpack('<H', binary.read(2))[0]
struct.error: unpack requires a buffer of 2 bytes


Gives me an error. I ask this cause was this just designed to deal with EXE file?

**Comment by aqua95** [comment]
sorry it works fine with DLL's as well. Cheers
