### ISSUE TITLE
sigthief.py: error: You must do something!

### ISSUE THREAD

**Issue by BTFighter** [secretsquirrel/SigThief#6]
I don't know if I'm doing something wrong, but trying to use this command: "sigthief.py -i real.dll -t test.dll -o clone.dll" doesn't work.
![Picture2](https://user-images.githubusercontent.com/45516471/129658886-f844214a-7f2e-4101-8120-5096e8420015.png)

Python (specifically 3.9.6) installed and SigThief.py is in the Tools folder with the two dlls inside the folder.

**Comment by secretsquirrel** [comment]
Is the input file signed? Try the -r flag. I can’t verify anything if I can’t get access to the files you are trying or if I do not have more details about your inputs.

**Comment by BTFighter** [comment]
Yes:
![Untitled4](https://user-images.githubusercontent.com/45516471/129727899-d34c558e-de56-481d-9fb3-8c17b526487e.png)

**Comment by secretsquirrel** [comment]
After looking at source, it shouldn’t even get to this based on this input. I’m wondering if it’s because you are on windows OS vs *nix or macOS. I’ll give it a look next time I’m around a computer.

**Comment by secretsquirrel** [comment]
Installed python3.9.6 from the windows App Store and works for me. 

You may need the newest version that is Open Source, do a git pull on the repo. 

Outside of that, it has to be something with your environment. I'm going to close this as I cannot repro your issue with the info provided. If you have anything that can help me repro, pls share. Thx!

<img width="919" alt="image" src="https://user-images.githubusercontent.com/1679850/129978927-d67c4020-2263-4b33-b5a4-fcaefecb2cdf.png">

**Comment by BTFighter** [comment]
Using another computer, I was able to rip the signature:
![image](https://user-images.githubusercontent.com/45516471/129989818-083b493c-354d-48e6-8379-4de24379af10.png)

You're right, there must be something wrong on my part, thanks for helping.

**Comment by secretsquirrel** [comment]
👍👍👍
